//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundVast.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MusicGenres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicGenres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundVast.Properties.MusicGenres", typeof(MusicGenres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Rock.
        /// </summary>
        internal static string AlternativeRock {
            get {
                return ResourceManager.GetString("AlternativeRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        internal static string Ambient {
            get {
                return ResourceManager.GetString("Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical.
        /// </summary>
        internal static string Classical {
            get {
                return ResourceManager.GetString("Classical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance &amp; EDM.
        /// </summary>
        internal static string DanceAndEDM {
            get {
                return ResourceManager.GetString("DanceAndEDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancehall.
        /// </summary>
        internal static string Dancehall {
            get {
                return ResourceManager.GetString("Dancehall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep House.
        /// </summary>
        internal static string DeepHouse {
            get {
                return ResourceManager.GetString("DeepHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco.
        /// </summary>
        internal static string Disco {
            get {
                return ResourceManager.GetString("Disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum &amp; Bass.
        /// </summary>
        internal static string DrumAndBass {
            get {
                return ResourceManager.GetString("DrumAndBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubstep.
        /// </summary>
        internal static string Dubstep {
            get {
                return ResourceManager.GetString("Dubstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic.
        /// </summary>
        internal static string Electronic {
            get {
                return ResourceManager.GetString("Electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold &amp; Singer-Songwriter.
        /// </summary>
        internal static string FolkAndSingerSongwriter {
            get {
                return ResourceManager.GetString("FolkAndSingerSongwriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip-hop &amp; Rap.
        /// </summary>
        internal static string HipHopAndRap {
            get {
                return ResourceManager.GetString("HipHopAndRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        internal static string Indie {
            get {
                return ResourceManager.GetString("Indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz &amp; Blues.
        /// </summary>
        internal static string JazzAndBlues {
            get {
                return ResourceManager.GetString("JazzAndBlues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin.
        /// </summary>
        internal static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        internal static string Metal {
            get {
                return ResourceManager.GetString("Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piano.
        /// </summary>
        internal static string Piano {
            get {
                return ResourceManager.GetString("Piano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        internal static string Pop {
            get {
                return ResourceManager.GetString("Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;B &amp; Soul.
        /// </summary>
        internal static string RAndBAndSoul {
            get {
                return ResourceManager.GetString("RAndBAndSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggae.
        /// </summary>
        internal static string Reggae {
            get {
                return ResourceManager.GetString("Reggae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundtrack.
        /// </summary>
        internal static string Soundtrack {
            get {
                return ResourceManager.GetString("Soundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno.
        /// </summary>
        internal static string Techno {
            get {
                return ResourceManager.GetString("Techno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string Trap {
            get {
                return ResourceManager.GetString("Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triphop.
        /// </summary>
        internal static string Triphop {
            get {
                return ResourceManager.GetString("Triphop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
